### ISSUE TITLE
INTERNAL ASSERT FAILED

### ISSUE THREAD

**Issue by denjots** [lucidrains/se3-transformer-pytorch#10]
Hi - I'm not sure if this is actually a bug or if I'm just expecting too much, but the following code snippet bombs with a PyTorch internal assert failure:

`RuntimeError: sub_iter.strides(0)[0] == 0INTERNAL ASSERT FAILED at "/opt/conda/conda-bld/pytorch_1618643394934/work/aten/src/ATen/native/cuda/Reduce.cuh":929, please report a bug to PyTorch.
`

That's using the latest PyTorch nightly. Tried with both CUDA 10.2 and 11.1.

Looking at the PyTorch bug reports, this seems to suggest that there is massive internal memory allocation being triggered when summing over a large tensor. It seems to have been sitting open for a year and I'm not sure if they even see it as an actual bug there. Certainly it doesn't seem to be a priority.

Problem with this is that this isn't a particularly large data input, or a large model (to say the least!), and my GPU has 40 Gb of RAM, so, scalability of this particular transformer model seems very minimal as it currently stands. Changing the dim from 128 to 64 does at least allow it to run.

```
import torch
from se3_transformer_pytorch import SE3Transformer

model = SE3Transformer(dim = 128, heads = 1, depth = 1, dim_head = 1, num_degrees = 1, input_degrees=1, output_degrees=1).cuda()

feats = torch.randn(1, 200, 128).cuda()
coords = torch.randn(1, 200, 3).cuda()

out = model(feats, coords)

```

**Comment by lucidrains** [comment]
@denjots Hi! Would you like to give 0.3.2 a try?

**Comment by lucidrains** [comment]
@denjots also try reversibility for depth

**Comment by denjots** [comment]
Brilliant as ever - even works with 4 layers and a decent number of heads now! Even without reversibility switched on.

**Comment by lucidrains** [comment]
@denjots i'll keep optimizing the heck out of this :)
