### ISSUE TITLE
small bug

### ISSUE THREAD

**Issue by MattMcPartlon** [lucidrains/se3-transformer-pytorch#16]
https://github.com/lucidrains/se3-transformer-pytorch/blob/7c79998e4d84ec6bd6b6d4b916c6bf30b870b75b/se3_transformer_pytorch/se3_transformer_pytorch.py#L301

should be `if isinstance(m,nn.Linear)`

nbd, but thought you might wanna know.

**Comment by lucidrains** [comment]
@MattMcPartlon thanks lol

how are things?

**Comment by lucidrains** [comment]
@MattMcPartlon you saw TTAFold right?

**Comment by lucidrains** [comment]
@MattMcPartlon https://developer.nvidia.com/blog/accelerating-se3-transformers-training-using-an-nvidia-open-source-model-implementation/

**Comment by MattMcPartlon** [comment]
Good! Just wrapped up a 3 month internship at FB. Hope you're doing well. Still doing comp. bio stuff? Tried to message you on discord, but they're getting rejected. 

I haven't looked at any recent literature. No time during the internship

Saw this code. I'm not actually sure what the real "innovation" is...  Have you tried it? It looks to me that the memory overhead will actually be worse in their top level mode (since pairwise conv kernels would require a factor 4 overhead if keys and values are combined). Will definitely be faster, but I'm mainly interested in memory. My current hack is just to use a smaller hidden dimension/head dimension for coordinates.

FYI:  training is slightly less stable with this bug fix lol.

**Comment by lucidrains** [comment]
@MattMcPartlon lol yes, i noticed equivariance was breaking too after the 'fix', so i'm just going to remove it :man_shrugging: 

good! i took on some contract work, so will be MIA for a month or two

friend me on Discord and we can chat that way :)
