### ISSUE TITLE
question about non scalar output

### ISSUE THREAD

**Issue by Chen-Cai-OSU** [lucidrains/se3-transformer-pytorch#5]
Hello,

I am interested in using your implementation on my dataset. There are two things I want to check with you
1) The property I want to predict is a 3x3 symmetric PSD matrix.
2) There are some edge features (one categorical feature, one continuous feature) besides the coordinate difference

I was wondering does the current se3-transformer can work with such a scenario? Thanks!

**Comment by lucidrains** [comment]
1. Is it a type 1 feature?
2. Yes! This repo accepts edges, just like Fabians official repo

**Comment by Chen-Cai-OSU** [comment]
It's not type 1 feature. It's more like a composition of type 0 and type 2 feature, which makes things tricky.

**Comment by lucidrains** [comment]
@Chen-Cai-OSU you can return type 2 features as well, just as the `output_degrees = 3`, and when you invoke forward, do a `return_type = 2`
